kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/BigQueryRecordConverter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/convert/BigQueryRecordConverterTest.java
This PR fixes a case, when schemaless has a map, and it has a `null` value, e.g.:
```
{"user-agent":"Chrome", "ts": 1540275907603, "url": null}
```
The root cause is a bug in JDK - https://bugs.openjdk.java.net/browse/JDK-8148463.
=> CC-7399: Handle null value if schema-less record has a map with a null value.

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/KCBQThreadPoolExecutor.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/TableWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTaskTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/convert/BigQueryRecordConverterTest.java
Background: 
The connector writes to BigQuery using a separate thread pool, which means that errors encountered during those writes don’t immediately cause the task to fail. Those errors aren’t swallowed silently, however, and do cause the task to throw an exception from its [`flush method`](https://github.com/wepay/kafka-connect-bigquery/blob/4fb38a8f4b3b6db065976639c57106db9896f0db/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java#L127) when invoking [`KCBQThreadPoolExecutor::awaitCurrentTasks`](https://github.com/wepay/kafka-connect-bigquery/blob/4fb38a8f4b3b6db065976639c57106db9896f0db/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/KCBQThreadPoolExecutor.java#L76-L100).
Unfortunately, the framework does not fail tasks when …
=> FMC-463: Fail task if error is encountered when writing to BigQuery

README.md, build.gradle, kcbq-api/src/main/java/com/wepay/kafka/connect/bigquery/api/SchemaRetriever.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/exception/ExpectedInterruptException.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/retrieve/MemorySchemaRetriever.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/utils/TableNameUtils.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/KCBQThreadPoolExecutor.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/MergeBatches.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/TableWriter.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/AdaptiveBigQueryWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTaskTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/MergeQueriesTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BaseConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/UpsertDeleteBigQuerySinkConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/retrieve/MemorySchemaRetrieverTest.java, kcbq-connector/src/test/resources/log4j.properties
[Jira](https://confluentinc.atlassian.net/browse/CC-8804)
Adds integration tests for upsert/delete and fixes a small bug in the connector's `SchemaRetriever` API. For instructions on running the tests, see the changes to the `README`.
The tests cover:
- Connector running in upsert-only mode, delete-only mode, and upsert-delete mode, with ingestion-time partitioning, automatic table creation (via the `MemorySchemaRetriever`), and correctness-of-content verification for all three.
There's also an ignored-by-default throughput test that generates 1,000,000 records into Kafka, runs the connector in upsert-delete mode, and outputs the time taken between starting the connector and commit of offsets for every record produced.
=> CC-8804: Integration tests for upsert/delete

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/exception/BigQueryConnectException.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/KCBQThreadPoolExecutor.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/TableWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTaskTest.java
In some cases, BigQuery connector exception in async thread are not surfaces. As a result, the worker trace only shows generic error message like `com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Encountered unrecoverable errors: org.apache.kafka.connect.errors.ConnectException\nMessage: Attempted to reduce batch size below 1.; See logs for more detail`. User has to go check the logs and see what happened. While this isn't a big issue for on-prem, it makes the cloud experience bad as user doesn't know what action they should take to fix the problem. And it adds to oncall burden.
Propagate error trace back to top level, so we can add error mapping to instruct users what they can do to make the connector work.
Currently, schema mismatch error is already in top level …
=> CC-9208: Include original trace in worker trace when task fails.

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/exception/BigQueryConnectException.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/KCBQThreadPoolExecutor.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/TableWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTaskTest.java
In a few cases where tasks fail or they don't fail but keep retrying, the underlying error is not shown in worker trace, including but not limited to:
- Destination table has no schema
- Table partitioned by timestamp column instead of ingestion time
- Add required fields to an existing schema
- User does not have bigquery.tables.updateData permission
Surface the underlying error.
=> CC-9208: Include original trace in worker trace when task fails. (#18)

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java
This log spams our ES logs very heavily.
Demote to debug. Already one in `181798e3b438b1`, but now will be hotfixed sooner.
=> Demote log level

build.gradle
Current connector image uses an outdated `kafka-connect-avro-converter`:
```
./gradlew kcbq-confluent:dependencies |grep avro|grep conver
+--- io.confluent:kafka-connect-avro-converter:5.5.0
+--- io.confluent:kafka-connect-avro-converter:5.5.0
+--- io.confluent:kafka-connect-avro-converter:5.5.0
+--- io.confluent:kafka-connect-avro-converter:5.5.0
+--- io.confluent:kafka-connect-avro-converter:5.5.0
+--- io.confluent:kafka-connect-avro-converter:5.5.0
+--- io.confluent:kafka-connect-avro-converter:5.5.0
+--- io.confluent:kafka-connect-avro-converter:5.5.0
+--- io.confluent:kafka-connect-avro-converter:5.5.0
```
There are some cloud incidents, caused by old versions of `kafka-connect-avro-converter`.
Bump up `ioConfluentVersion` to `5.5.1` so that `kafka-connect-avro-converter:5.5.1` is …
=> RCCA-1483: Bump up ioConfluentVersion to 5.5.1 to include the latest kafka-connect-avro-converter.

kcbq-connector/test/integrationtest.sh
The integration tests don't use the new `defaultDataset` config property and instead rely on the old `datasets` property.
Update the integration tests to use the new property.
N/A
Patch the integration test script, then run the integration test.
Target 2.0.x (the earliest affected branch) and, after merging, port forward into master.
=> MINOR: Fix integration test to use new datasets config property

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/AdaptiveBigQueryWriter.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/GCSToBQWriter.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/UpsertDeleteBigQueryWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java
Addresses #27 by adding an `allowSchemaUnionization` config property that defaults to `false` and dictates whether schema unionization should occur during schema updates. Unit tests for the `SchemaManager` class (where the bulk of this logic is located) are added to verify expected behavior.
=> GH-27: Add allowSchemaUnionization config property

kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriterTest.java
This mimics a [change made on 2.0.x](https://github.com/confluentinc/kafka-connect-bigquery/blob/3aec4fd720d2a1cacd77ed2250addcd7d7d9df10/kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriterTest.java#L124); should have been applied back onto 1.6.x. Doing so here to fix the build.
=> MINOR: Fix BigQueryWriterTest unit test

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/utils/FieldNameSanitizer.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/utils/FieldNameSanitizerTest.java
Addresses https://github.com/confluentinc/kafka-connect-bigquery/issues/39, by converting Java 8 streams to a simpler `Map::forEach` invocation. Adds two tests to verify that null inner values (even if nested deeply) do not cause any issues with sanitization, and the existing tests provide sufficient coverage to give us confidence that the changes here don't break the other parts of the field sanitization logic.
=> GH-39: Fix NPE when null inner values are encountered with field sanitization enabled

pom.xml
These dependencies are used for integration testing only and should not be packaged with the connector.
=> MINOR: Fix scope for test dependencies (Avro converter, Schema Registry, etc.)

README.md, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BaseConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQuerySinkConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/UpsertDeleteBigQuerySinkConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/utils/BucketClearer.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/utils/TableClearer.java, pom.xml
Addresses https://github.com/confluentinc/kafka-connect-bigquery/issues/41, with the strategy proposed in the issue:
1. We've set a conservative retention policy of 24 hours on the dataset we use for integration testing the connector
2. We've altered the integration tests for the connector to use an optional `$KCBQ_TEST_TABLE_SUFFIX` environment variable which, if present, is appended to the end of each table created during integration tests
3. We've modified the Jenkins profile in the top-level pom to populate that environment variable and `$KCBQ_TEST_FOLDER` with the branch name, git commit hash, epoch timestamp for the run, so that we can easily identify which test runs correspond to which tables in the event that there's a failure we'd like to investigate
=> GH-41: Fix concurrent integration test runs on Jenkins

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/BigQuerySchemaConverter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/convert/BigQuerySchemaConverterTest.java, pom.xml
The schema conversion doesn't handle schemas that contain recursive cycles. Rather than fail with a generic `StackOverflowError`, try to detect cycles and throw a `ConversionConnectException`.
=> CC-12157: Throw nicer exception on detecting cycle in schema

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/TableWriter.java
We've started seeing this exception in the logs for the connector:
```
[WARN] 2020-10-16 10:01:25,429 [pool-7-thread-8] com.wepay.kafka.connect.bigquery.write.batch.TableWriter run - Could not write batch of size 176 to BigQuery.
com.google.cloud.bigquery.BigQueryException: Request payload size exceeds the limit: 10485760 bytes.
at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:103)
at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.insertAll(HttpBigQueryRpc.java:377)
at com.google.cloud.bigquery.BigQueryImpl$21.call(BigQueryImpl.java:773)
at com.google.cloud.bigquery.BigQueryImpl$21.call(BigQueryImpl.java:770)
at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
at …
```
=> MINOR: Catch 'request payload exceeds size' errors from BigQuery and reduce batch size in response

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java
Addresses https://github.com/confluentinc/kafka-connect-bigquery/issues/50.
We don't need to preemptively check for the existence of tables at all, as the end result will be the same regardless (the connector will fail if table creation is disabled and receives records destined for a table that does not already exist). The current preemptive check makes it extremely easy to run up against BigQuery rate limits, and the additional complexity of retaining the check with some kind of caching layer doesn't seem worth the benefit it provides, so right now I think it's best to just remove it altogether.
=> GH-50: Remove maybeEnsureExistingTable method

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/exception/BigQueryConnectException.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/KCBQThreadPoolExecutor.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/TableWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTaskTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriterTest.java
This back ports https://github.com/confluentinc/kafka-connect-bigquery/pull/14 and https://github.com/confluentinc/kafka-connect-bigquery/pull/18 into the 1.6.x branch. 
Please see https://github.com/confluentinc/kafka-connect-bigquery/issues/55. 
Tests are passing however I have not been able to test this directly against BigQuery.
=> 1.6.x backports

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTaskTest.java
Addresses #68, by causing calls to `flush` to fail even if the task has already been stopped.
=> GH-68: Continue to check for errors in flush even after stopped

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkTaskConfigTest.java
Schema Retriever has no default currently and customers are confused on why that is the case/ whether Identity Schema Retriever should cover their use cases. The Identity Schema Retriever should cover most use cases and hence should be made the default.
https://github.com/confluentinc/kafka-connect-bigquery/issues/75 
Make Identity Schema Retriever the default. 
Cut release 2.0.0 with this change
=> GH-75: Make IdentitySchemaRetriever the default schema retriever for BQ 2.0.0

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfigTest.java
Addresses https://github.com/confluentinc/kafka-connect-bigquery/issues/80
Adds a new configuration property, `timePartitioningType`, that controls which time partitioning type to use for automatically-created tables. Valid values are (case-insensitive) `HOUR`, `DAY`, `MONTH`, or `YEAR`, and if any additional time partitioning types are added to the Java BigQuery SDK, those should be picked up automatically as well.
Existing test coverage was pretty good for this, so I only modified one unit test and added three new ones.
=> GH-80: Add support for configuring time partitioning type on created tables

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkTaskConfig.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkTaskConfigTest.java
Co-authored by: Philippa Main <philippa.main@autotrader.co.uk>
on-behalf-of: @autotraderuk <dataengsupport@autotrader.co.uk>
Add partition expiration to a table. Partition expiration removes
partitions from the table after a specified amount of time.
It is an optional field in the connector.
=> Add partition expiration

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java
We are using v2.0.0. Several instances encountered NPE at https://github.com/confluentinc/kafka-connect-bigquery/blob/52c5451683dacfcee054c7d6721f386bad9d05bb/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java#L389-L390 . So either `currentField.getMode()==null`, or `proposedField.getMode()==null`. According to google's doc https://cloud.google.com/bigquery/docs/schemas#modes , `mode==null`, or mode is unspecified, is equivalent to `mode==NULLABLE`. 
To mitigate the issue, and to help with further debugging, I made two changes on top of 2.0.x:
1.  While retrieving fields from BigQuery schema, the connector does an additional check to see if the mode is unspecified, or in other words, equals `null`, and if so, set it to its equivalence, NULLABLE;
2. Add a …
=> Prevent NPE thrown at SchemaManager.isFieldRelaxation() by specifying unspecified field mode as NULLABLE

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/AdaptiveBigQueryWriter.java
We've had some reports that the connector fails (especially when upsert/delete is enabled) after creating a new table because it keeps getting 404 errors. After bumping this value the errors stopped and the connector was able to work smoothly.
=> MINOR: Increase retry period for writes after table creates/updates to 15 minutes

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java
Addresses https://github.com/confluentinc/kafka-connect-bigquery/issues/96.
The only field mode that doesn't allow `NULL` values is `REQUIRED`; the `REPEATED` and `NULLABLE` modes both permit `NULL`. So, when performing schema updates, we don't need to relax new `REPEATED` fields to `NULLABLE`, and can instead leave them as `REPEATED`.
=> GH-96: Fix unionization/update logic for REPEATED fields

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/AdaptiveBigQueryWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java
https://github.com/confluentinc/kafka-connect-bigquery/pull/99 attempted to fix schema unionization logic for `REPEATED` fields but missed an important case: when the `REPEATED` field was present in one of the schemas seen, but missing from a later schema (as opposed to being added at a certain point, and contained in all subsequent schemas).
This fix addresses that case and verifies behavior by expanding on an existing unit test.
=> GH-96 (follow-up): Include REPEATED fields in unionized schemas if missing from later schemas

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfigTest.java
Addresses #105
Now, if users specify a `timePartitioningType` of `NONE` in their connector config, any tables automatically created by the connector will not be partitioned at all.
I considered adding validation to make sure that if `NONE` is specified, no values for `timestampPartitionFieldName`, `partitionExpirationMs`, or `clusteringPartitionFieldNames` are provided. Ultimately I'm not sure that's really necessary and there's already some precedent for leaving out similar validations such as ensuring that all of these properties are only specified when `autoCreateTables` is `true`.
Two unit tests are added to verify the new behavior.
=> GH-105: Allow creation of non-partitioned tables

kcbq-connector/quickstart/properties/connector.properties
These properties haven't been used by the connector for a long time; we should remove them from the code base in order to avoid confusing users.
=> MINOR: Remove outdated properties

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/BigQuerySchemaConverter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/convert/BigQuerySchemaConverterTest.java
The connector throws an NPE when it hits a tombstone with null value schema record if delete is enabled.
Reproduced with the following conditions:
Connector has upsert and delete enabled,
Table has timestamp filed partition,
Tombstone message has null value.
Sample log.
[timestamp] TRACE: Applying transformations to record in topic 'test_topic' partition 1 at offset 11111 and timestamp 1621599043906 with key Struct{KEY=1234567} and value null (org.apache.kafka.connect.runtime.WorkerSinkTask:518)
Stack trace on v2.1.3
```
java.lang.NullPointerException
at com.wepay.kafka.connect.bigquery.convert.BigQuerySchemaConverter.convertSchema(BigQuerySchemaConverter.java:104)
at com.wepay.kafka.connect.bigquery.convert.BigQuerySchemaConverter.convertSchema(BigQuerySchemaConverter.java:46)
at …
```
=> Prevent records with null value schema from causing NPE when delete is enabled

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java
The previous attempt [PR117](https://github.com/confluentinc/kafka-connect-bigquery/pull/117) to fix an NPE thrown when record value is null (tombstone) had 2 problems:
1. If unionization is not turned on, it would disallow tombstone records when proposing a new BigQuery schema. Delete wouldn't not be supported.
2. Another NPE which was covered by previous NPE was exposed, because tombstone records were passed to `getUnionizedTableDescription`
To fix the above 2 issues, this PR does:
1. Revert the behavior of not allowing tombstone records when unionization is turned off.
2. Change the behavior of only checking the last record from the batch when proposing new schema when unionization is turned off. Instead, `SchemaManager` would look for a regular record with non-null value schema. In …
=> Skip record with null valueSchema when proposing new BigQuery schema.

pom.xml
As mentioned in https://github.com/confluentinc/kafka-connect-bigquery/issues/98, `mvn clean package -DskipTests` fails with maven 3.8.1 because the external HTTP repository is blocked by default. https://maven.apache.org/docs/3.8.1/release-notes.html
Why don't you use `https` instead?
=> Use https://packages.confluent.io/ instaed of http

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/TableWriter.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/AdaptiveBigQueryWriter.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryErrorResponses.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryErrorResponsesIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriterTest.java
Addresses https://github.com/confluentinc/kafka-connect-bigquery/issues/144
A new `BigQueryErrorResponses` class is added that isolates the logic for classifying error responses from BigQuery. Classes that used to perform their own error classification are updated to leverage this new class instead. An integration test suite is added for this new class that covers some but not all types of errors; some, such as backend errors and rate limit errors, are difficult or even impossible to test reliably.
The 2.0.x branch is targeted in order to leverage the new integration testing infrastructure introduced there. This can be backported to 1.6.x if there is significant demand and someone willing to file the PR.
=> GH-144: Isolate error classification logic into single, testable class

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/exception/BigQueryConnectException.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriter.java
The current logging information is hard to track which table and which column is related to BigQueryConnectException. This PR adds the table/column information to logs so that the error message would be more complete and easy to track. Would you please take a look at this small change? Thanks!
=> adding table and column information to help debugging

kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BaseConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQuerySinkConnectorIT.java
Addresses https://github.com/confluentinc/kafka-connect-bigquery/issues/146
This is a little more complicated than just adding the `@Parameterized` runner to the tests. Since they currently use a single embedded Zookeeper, Kafka, Connect, and Schema Registry worker that's shared among all test cases, the same behavior is preserved here in order to avoid inflating the build time with setting up/tearing down these services for each individual case.
Each test case now uses a different connector (to make it possible to run several test cases in a single build and get a more granular signal of success/failure for each of them), but they still share a single embedded instance of Connect, SR, etc.
In order to accomplish, the test class is modified to no longer inherit from `BaseConnectorIT` but …
=> GH-146: Parameterize BigQuerySinkConnectorIT tests

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryErrorResponses.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryErrorResponsesIT.java
Previously, if a table was deleted and recreated in a short time period, some writes to that table ran the risk of being silently dropped by BigQuery.
It seems like BigQuery handles that case now by returning a new error for writes to recently-recreated tables with the same 404 code and `notFound` reason, but a slightly different message (something like "Not found: table Table is deleted: &lt;table&gt;" (the "table Table" part is not a typo; this is what the responses actually look like)).
We can handle this new error the same way we handle missing table errors already. It may not be super useful for everyday users of the connector but it makes integration testing (and possibly upsert/delete logic) much easier since we can now wipe out tables left over from previous tests and then spin up …
=> MINOR: Handle new "table is deleted" error from BigQuery

Jenkinsfile, README.md, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/GcpClientBuilder.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/CredentialsValidator.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/CredentialsValidatorTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BaseConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/GcpClientBuilderIT.java
Support Application Default Credentials (ADC) to allow finding credentials automatically if deployed in GCP.
If kafka connect runs inside a Google Cloud environment, is possible to attach a service account to that environment, so the application can retrieve credentials for the service account without having to create and manage keys. 
https://cloud.google.com/docs/authentication/production
Its also possible to use this method outside GCP by setting the **GOOGLE_APPLICATION_CREDENTIALS** env var with the path to the credentials file.
=> Support Application Default Credentials (ADC) to find credentials automatically in GCP

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java
Addresses https://github.com/confluentinc/kafka-connect-bigquery/issues/164
Verified locally by running the connector on Connect 2.3.
=> GH-164: Remove dependency on ConfigDef.CaseInsensitiveValidString

Jenkinsfile, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryErrorResponsesIT.java
The jenkins build was failing as it takes more than 1 hour with the new versions (2.x.x)
Increased the timeout to 2 hours in jenkins file.
=> Fixed test and increased jenkins timeout

Jenkinsfile, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/GcpClientBuilder.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTaskTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfigTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BaseConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryErrorResponsesIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriterTest.java
User-agent Header needs to be added for GCP calls from the connector to track connector usage.
We have created an internal config for Product name. We will use this config to populate the appropriate product in the header.
- [ x] no
- [ x] Integration tests
=> Added user-agent header for GCP calls

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryErrorResponses.java
Signed-off-by: Aakash Shah <ashah@confluent.io>
[isMissingRequiredFieldError](https://github.com/confluentinc/kafka-connect-bigquery/blob/03858c71f50b30daa42630150a498d17b5dbff8e/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryErrorResponses.java#L115-L118) only accounts for one missing field, which is presented by "Missing required field:", and if there are multiple missing fields, the error shows "Missing required fields:". Thus, if multiple fields are missing, the connector does not treat that error as an invalid schema error.
Adjust `isMissingRequiredFieldError` to account for both errors by adjusting the `startsWith()` call.
Backport to 2.0.x
=> RCCA-7127: Adjust error identification to include multiple missing fields

README.md, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, pom.xml
CCDB-4929: Adding error messages for union operation failure cases.
This issue was seen a bunch of times during on-call and because there was no error message available rather just based on stack trace we couldn't classify these errors previously.
**PS**: Targeting 2.0.x as the original code change got introduced there ([PR-121](https://github.com/confluentinc/kafka-connect-bigquery/pull/121))
=> CCDB-4929: Adding error messages for union operation failure cases.

pom.xml
Previously I did the changes directly on master by mistake ([PR](https://github.com/confluentinc/kafka-connect-bigquery/pull/216)). Now as part of this PR, doing the same change on branch 2.3.x.
=> Fixing CVEs: CCDB-4936, CCDB-4836 & CCDB-4835.

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfigTest.java
Adding topic2table map config support to BQ sink connector. This way users can directly configure what table should records from a given topic be ingested into. I have tested on docker playground the following scenarios =>
1) sanitizeTopic flag is ignored when topic2TableMap is supplied. So, whatever table name is specified in the map would be used as is.
2) If the topic name in the record is not in the topic2TableMap, then the topic name would be used as the table name.
=> CCDB-5048: Adding topic2table map config support to BQ sink connector

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/MergeQueriesTest.java
Adding table in queries to avoid exception such as "UPDATE ... SET does not support updating the entire row at [11:7]"
SQL requires a uniquely identifiable field in queries. If they have the same name, without alias, they are not unique. This fixes the issue
This happens when the table name and a column name have the same name
=> Fix MERGE query for tables with columns that have the same name of the table

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTaskTest.java, pom.xml
This PR adds more uniqueness to generates GCS filename by appending _[OFFSET] at the end as kafka record offsets are unique. 
This change is needed as we receive 'Missing record' issue from customers for BigQuery Batch mode. After overriding record consumption property `consumer.override.max.poll.records=1` by 1 and keeping rest of the code same, we could locally observe lesser number of records in BQ table. This happens as multiple files with same name get generated by a task in 1 millisecond and GCS only keeps 1 file with a unique name as live version (others are marked as non-live versions).
This is hard to reproduce with default poll count of 500 (we could not reproduce the issue after multiple re-tries with 500 poll rate).
Appending offset (which is different for each record) makes …
=> CCDB-5226 Adding more uniqueness to GCS blob object filename 

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/MergeBatches.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/MergeQueriesTest.java
The MergeFlush method in BQ SinkConnector for upsert/delete mode keeps increasing batch number even if the current batch has 0 records. This results in 
- unnecessary resource consumption
- unexpected behaviour as empty batches are also processed just like any other batch. 
This PR fixes empty batch creation by preventing batch creation when current is not initialised or there are no records in current batch.
Below recording shows the sequential completion of records 
https://user-images.githubusercontent.com/117655560/209628904-33863fa2-afad-4099-957a-d21b1a3037fc.mov
=> Ccdb 5286 fix empty batches creation

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/UpsertDeleteValidator.java
This PR does following -
1. Logs warning if mergeIntervalMs config is set to less than 10 sec. The corresponding validation is not added due to backward compatibility concerns. Read here to understand why we need a lower limit on this config. https://confluentinc.atlassian.net/browse/CCDB-5274?focusedCommentId=1279019
2. Updates documentation for point 1
3. Updates documentation for validation 1 mentioned in description https://confluentinc.atlassian.net/browse/CCDB-5287 
Updated documentation text and logged warning screenshots -
=> CCDB-5287: updates documentation for configs, logs warning if mergeIntervalMs lower limit is not met

pom.xml
Vulnerable dependency "protobuf-java" for kafka-connect-bigquery
CVE: https://confluentinc.atlassian.net/browse/CCDB-5307
Upgrading to 3.19.6 from 1.1.x onwards
Will do ping merge after PR merge
`mvn dependency:tree` output
-  Tested the changes via kafka docker playground. Modified [this](https://github.com/vdesabou/kafka-docker-playground/blob/master/connect/connect-gcp-bigquery-sink/gcp-bigquery-sink.sh) script which generates data to send to kafka which is consumed by bigquery sink connector to send to BigQuery DW.
-   <img width="840" alt="Screenshot 2023-01-13 at 7 14 56 PM" src="https://user-images.githubusercontent.com/121012039/212334933-453fc42a-7077-42db-bcb7-3e6b52150d44.png">
=> [CCDB-5307] Upgrade protobuf-java to 3.19.6

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/MergeQueriesTest.java
This PR backports merged changes from 2.4.x into 2.3.x for [CCDB-5197 ](https://confluentinc.atlassian.net/browse/CCDB-5197) as release of 2.4.x on cloud is right now blocked. 
This is a bug fix. 
Original PR with changes (merged in 2.4.x) : https://github.com/confluentinc/kafka-connect-bigquery/pull/238/commits
=> Cc 18817 backport changes of ccdb 5197 to 2 3 x branch

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/BigQueryRecordConverter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/convert/BigQueryRecordConverterTest.java
…behind a config for BigQuerySink Connector
Refer to [this](https://confluentinc.atlassian.net/browse/CCDB-4843) ticket for details related to testing and Release Plan
=> [CCDB-4843] Register TimestampConverter in DebeziumLogicalConverters behind a config for BigQuerySink Connector

kcbq-api/pom.xml, kcbq-connector/pom.xml, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfigTest.java, pom.xml
This PR updates Pom file to include client library and required configs for the new API. 
Includes - 
1. google cloud bom as documented here : https://cloud.google.com/bigquery/docs/reference/storage/libraries#install 
2. Cleanup of pinned protobuf-java and auth dependency as the latest bigquery version brings in  these.
3. Configs required from one-pager https://confluentinc.atlassian.net/wiki/spaces/CONNECT/pages/2961999467/Storage+Write+API+in+BQ+Sink+Connector#StorageWriteAPIinBQSinkConnector-User-FacingChanges 
JIRA tickets : https://confluentinc.atlassian.net/browse/CC-19645 , https://confluentinc.atlassian.net/browse/CC-19657 
Epic : https://confluentinc.atlassian.net/browse/CC-19644
=>  Storage Write API Client library and configs addition

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiBase.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiDefaultStream.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiDefaultStreamTest.java
This PR adds shutdown method which is responsible for closing all json writer opened in a task. 
This will be called by task.stop() method while shutting down.
JIRA : CC-19650
Epic : CC-19644
=> Storage Write API Default stream resource cleanup on task shutdown

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/StorageWriteApiValidator.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/StorageWriteApiValidatorTest.java
This PR adds validation checks for Storage Write API basic and batch mode.
- New api cannot be clubbed with any of legacy modes
- New Batch mode can only be enabled if connector is configured to use new api. 
- Unit tests to test the validation
JIRA : CC-19905
EPIC: CC-19644
=> Storage Write api mode validation

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTaskTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQueryStorageApiSinkTaskTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SinkPropertiesFactory.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BaseConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriterTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/GCSToBQWriterTest.java
This PR adds
-> Task start for creating default stream 
-> Task put to send records via new api if configured
-> Task stop for cleaning up resources
-> Corresponding unit tests
-> Fixes unit tests failure due to newly added validations
JIRA: CC-19795
Epic: CC-19644
=> Storage Write API Adds SinkTask Methods (start, put, stop)

Jenkinsfile
Due to addition of more Integration tests for Storage Write API, the build is failing at 2 hours due to timeout.
This PR increases the Jenkins build timeout to 3 hours to handle the time duration increased by new tests.
=> Increasing Jenkins build timeout to 3 hours

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiBase.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiDefaultStream.java
This PR fixes malformed entries from Javadoc. 
Release on 2.6.x is failing due to bad error. Please take a look at the detailed logs for build #2324
```
error: malformed HTML
error: bad use of '>'
```
=> Fixes Storage Write API default stream java docs

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQueryStorageApiSinkTaskTest.java
This PR updates 'null' to default in case of default streams. This change only improves trace logging as this string is not used anywhere else.
=> Storage Write API: changes stream name from null to default 

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/KafkaDataBuilder.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/convert/KafkaDataConverterTest.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiWriterTest.java
Legacy API sends kafka record details with insertTime as double. This logic was kept same but during testing it was found not working. 
After working with Google support team we got to know that the new API expects int(64)/microsecond timestamp  snd double is not supported. (Documented here - https://cloud.google.com/bigquery/docs/write-api#data_type_conversions)
This is a single usage in the connector where we are adding timestamp value. 
JIRA: CC-20247
=> BugFix: Storage Write API TImeStamp schema type accepts int64(long). 

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/exception/BigQueryStorageWriteApiErrorResponses.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiRetryHandler.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/exception/BigQueryStorageWriteApiErrorResponsesTest.java, pom.xml
This PR updates libraries-bom version to 26.14.0 to pull schema related changes of bigquerystorage write api which are added in 2.36.1 [version](https://github.com/googleapis/java-bigquerystorage/releases/tag/v2.36.1) 
This PR adds fixes a log message (identified during testing) and updates the unknown field check error message as changed [here](https://github.com/googleapis/java-bigquerystorage/pull/2048/files#diff-54b8d28cbcc58e884c960e2f5d8d11248aa3c8d6775a48c5adad6ff577c57448L374)
=> Storage Write API libraries bom version update

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java
This PR updates default value of useStroageWriteApi to false so the changes are turned off in initial release
=> Storage Write API config default update

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiBatchApplicationStream.java
Removes '<' and '>' from javadoc as release is failing. Build no 2369
=> Removes special chars from javadoc

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQueryStorageApiBatchSinkTaskTest.java
Problem: Storage APi in batch mode relies on the background thread which creates new streams and commits the older streams every commitInterval. If due to any reasons this background thread encounters any exception, it stops any further processing. This happens silently and we are not informed. The connector keeps running and put method keeps on receiving data but we do not commit anything to bigquery tables.
Solution: We now fail the task on seeing any errors in background thread. 
A reference discussion for this probelm is [here](https://stackoverflow.com/questions/6894595/scheduledexecutorservice-exception-handling) but the suggestions were not applicable in our case.
JIRA: CC-20491
=> Storage Write API Batch mode: Fail task when background thread throws an exception

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/ApplicationStream.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/ApplicationStreamIT.java
This PR fixes the data loss issue observed intermittently on devel for Storage Write API batch mode.
Cause: After investigation it was figured out that the stream got closed (we are still figuring out if this was initiated by our application or bigquery api) mid processing. The application recreated the stream but only committed the data carried by last stream.
Resolution: We are storing all streams created/recreated on an object and finalising and committing all at the end of processing.
Test:
Manual test
Integration test
=> Storage Write API Bug Fix : Commit streams which close mid processing

README.md
This PR adds documentation links for Basic, Batch (new API) and upsert/delete (Legacy API) in README.md
The docs access permission would be made public after PR merge. 
JIRTA: CC-19870
=> Add Implementation doc links in Readme

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java
**Issue -** 
The BigQuery iInk connector when configured with `allowSchemaUnionization` merges schema from BQ table and all the records of current batch and attempts schema update with unionized schema in BQ tables.
If the case of a field among table schema or any of the records schema does not match, connector today considers it as different column and tries to push all such entries in one schema request. This results in column `*** already exists in schema `errors from BigQuery.
**Fix -** 
SchemaManager maintains an internal map keyed with column names string and sends all the values of the map to bigquery. Have added `.toLowercase()` method on the map keys so the comparison can detect duplicates. Since the keys are used for internal processing, changing case would not be appearing on …
=> Fix duplicates with schema unionisation when column name case differs

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiWriter.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryErrantRecordHandlerIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQuerySinkConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryStorageWriteApiBatchSinkConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryStorageWriteApiSinkConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/TimePartitioningIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/UpsertDeleteBigQuerySinkConnectorIT.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/UpsertDeleteBigQuerySinkConnectorWithSRIT.java
**Upsert/delete functionality**
Upsert/delete mode is recommended with tasks.max=1.
Due to many records, 5 minutes timeout can be exceeded. Reducing record count from 20 to 8. 
Changed the topic name in SR and non-SR tests to prevent any issues due to parallel execution of tests.  
**Time Partitioning**
Increasing timeout to 5 minutes (defaults for most cases)
Changing comparison logic to match at least #number_of_records 
**DLQ routing**
Uniqueness to topic names
Reduced batch mode record count
Increased batch mode timeout due to presence of commit interval
**Legacy Batch mode**
Uniqueness to bucket name
**Storage API basic and batch** 
Uniqueness to table name
POM: Adds 'verify' goal in failsafe execution to include test result in Jenkins build status
JIRA: CC-20108
=> Fixes BigQuery IT flakines and verify goal to include IT result in Jenkins build

Jenkinsfile
Release job requires getVaultSecretsList() to be present if connector specific secrets loading is required.
JIRA: CC-21230 (contains the reference of why these changes are needed)
=> Updates Jenkinsfile to add release requirements for external secrets

Jenkinsfile
The existing Jenkins job fails to download the latest version of common-tools, which is needed for some standard Jenkins job logic.
Use the `docker-debian-jdk8` node type instead of the existing one. This node type is as similar to the existing node type as possible and successfully downloads the latest version of common-tools. The same approach was taken on a similar repo a couple years ago: https://github.com/confluentinc/kafka-connect-sqs/pull/30
The 21 other references to this node: https://github.com/search?q=org%3Aconfluentinc+docker-oraclejdk8+NOT+is%3Aarchived&type=code
PR job makes it past the existing issue
Merge to master and hope it works.
=> Update Jenkinsfile to use docker-debian-jdk8

pom.xml
CC-21199 : Pins Guava version to non-vulnerable
=> CC-21199 : Pins Guava version to non-vulnerable 

pom.xml
Fixes the guava vulnerability coming from transient dependency. 
Please check twistlock for green build.
=> pins auto-value dependency

kcbq-connector/pom.xml, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/GCSToBQLoadRunnable.java, pom.xml
Java’s util.Regex.Pattern is not a linear time regex parser and security advised to move to re2j.
JIRA for details: CC-20305
Ref: https://github.com/google/re2/wiki/Syntax
=> Replaces regex with re2j

README.md
Updates Readme to add Confluent Hub as downloadable option and remove maven
=> FF-12180: Updates README.md

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfigTest.java
like snowflow sink connector, it would be nice to have this.
[https://github.com/snowflakedb/snowflake-kafka-connector/pull/459](https://github.com/snowflakedb/snowflake-kafka-connector/pull/459)
I haven't written an integration test code because integration tests don't work well locally. Do I need to?
=> Support n:1 to topic2TableMap (topic:table)

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/utils/SleepUtils.java, kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryErrorResponses.java, kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/MergeQueriesTest.java
This is a fix for #349 to retry when the error is a jobInternalError (400)
After contacting support this error should be rare and can happen during system overload 
The documentation mention this "Retry the job with a new jobId. If the error continues to occur, contact support."
So I reused the existing catch for the retriable serialization error, since this error happen during system overload it can be relevant to wait few seconds before retrying.
I am open to any suggestion.
=> Fix #349 retry on jobInternalError

pom.xml
The scope of jackson dependency changed to **test** from 2.0.x onwards, due to which the build started failing corresponding to the new filtering changes.
=> Fix failing build

pom.xml
Bumps jackson core dependency to non-vulnerable version. 
```
bhagyashree@J6FQLC2XVG bigquery-storage-write-api % mvn dependency:tree  | grep jackson.core
[INFO]    |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.16.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.16.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.16.2:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.16.2:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.16.2:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.16.2:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.16.2:compile
```
=> Bumps Jackson dependency version to 2.16.2

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java
This PR removes the datatype validation check as it is incorrect. This check will false report datatype mismatches when the existing table schema does not match with connector generated schema. 
For example: Imagine a BigQuery table exists with Schema : 
```
Field Name: "f1"
DatType: BigDecimal
```
There is an input of below format : 
`{"f1":123,"f2":"abc"}`
The connector is configured to autoUpdateSchema with 
```
"allowNewBigQueryFields": "true",
"allowBigQueryRequiredFieldRelaxation":"true",
"allowSchemaUnionization":"true",
```
Due to `allowSchemaUnionization`, the connector would first fetch the existing table Schema and then would try to unionize the existing schema with the generated schema based on the input record 
```
Field Name: "f1"
DatType: Integer
Field Name: "f2"
DatType: …
```
=> Removes data type validation check

pom.xml
Address CONMON CVE on kafka_2.12
```
docker export fedramp-image | tar tvf - | grep kafka_2.12
-rw-r--r--  0 65532  65532   4485205 Apr 14 20:55 usr/share/java/connectors/plugins/kafka-connect-bigquery-cloud/kafka_2.12-2.6.0.jar
```
=> [CONMON-4341] Update kafka.version to fix CVE on org.apache.kafka:kafka_2.12
