confluentinc/kafka-connect-bigquery

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkConnector.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkTaskConfig.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/BigQueryRecordConverter.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/BigQuerySchemaConverter.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/GCSBatchTableWriter.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/KCBQThreadPoolExecutor.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/MergeBatches.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/TableWriter.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/AdaptiveBigQueryWriter.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/UpsertDeleteBigQueryWriter.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkConnectorTest.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTaskTest.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/MergeQueriesTest.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SinkPropertiesFactory.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SinkTaskPropertiesFactory.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkTaskConfigTest.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriterTest.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/GCSToBQWriterTest.java

[Jira](https://confluentinc.atlassian.net/browse/CC-8803)
This implements the changes proposed in the [collaborative design doc](https://docs.google.com/document/d/1p8_rLQqR9GIALIruB3-MjqR8EgYdaEw2rlFF1fxRJf0) for upsert/delete support in the connector.

CC-8803: Add support for upsert/delete via periodic merge flushes

---

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/utils/FieldNameSanitizer.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/utils/FieldNameSanitizerTest.java

Signed-off-by: Aakash Shah <ashah@confluent.io>

Add specific error if santizing field names throws NPE

---

Jenkinsfile
config/checkstyle/suppressions.xml
kcbq-connector/pom.xml
kcbq-connector/test/integrationtest.sh
pom.xml

This should be all that's left to integrate the connector into our CI/CD pipeline.
This'll add a Jenkins builder for PRs and, periodically and post-merge, feature branches and master. After https://github.com/confluentinc/kafka-connect-bigquery/issues/31 has been addressed, we'll also be able to automatically run integration tests.

MINOR: Add Jenkinsfile

---

kcbq-connector/pom.xml

- Update docs URL path to exact path (currently its redirecting but we're updating now to have a clean trail)
- Please let me know if I should target a different branch for this one and will do if needed.
- Update docs URL path to exact path

Update docs URL path

---

kcbq-connector/pom.xml

Update the Confluent Hub support summary for the connector.

Update supportSummary for BigQuery Sink

---

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/SchemaManager.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/SchemaManagerTest.java

BigQuery fields allow for subfields for the type `RECORD` . The current unionizing logic does not account for the fact that each field on the schema could potentially be a `RECORD` type with its own subfields. The consequence is that users setting `allowSchemaUnionization` and `allowNewBigQueryFields` set to true, expecting the BQ table to be evolved instead does not see the table being evolved and instead gets an error failing to insert to the table:
```
[BigQueryError{reason=invalid, location=mergedproduct.qualitybysellingarea[0].statusAsString, message=no such field: statusAsString.}], 2=[BigQueryError{reason=invalid, location=mergedproduct.qualitybysellingarea[0].statusAsString, message=no such field: statusAsString.}]
```
This PR fixes the unionization logic to recurse into …

Recursively unionize subfields

---

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/logicaltype/DebeziumLogicalConverters.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/convert/logicaltype/DebeziumLogicalConvertersTest.java

Fixes #161
(See https://github.com/debezium/debezium/blob/672f9588531be5c5426cef10ee733878174afada/debezium-core/src/main/java/io/debezium/time/Time.java#L29-L43)

[GH-161] Fixed cast error of Long in debezium time converter

---

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/exception/BigQueryConnectException.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriter.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryWriterTest.java

The previous related pull request (adding table and column information to help debugging #152) didn't fix the problem. The table info is passed into the exception function this time. The related unit test function is also changed for test purpose.

Add exception message

---

pom.xml

CCDB-4929: Fixing "Code scanning"/CodeQL warnings.

CCDB-4929: Fixing "Code scanning"/CodeQL warnings.

---

pom.xml

Draft PR w.r.t CVEs: [CCDB-4936](https://confluentinc.atlassian.net/browse/CCDB-4936), [CCDB-4836](https://confluentinc.atlassian.net/browse/CCDB-4836) & [CCDB-4835](https://confluentinc.atlassian.net/browse/CCDB-4835).
PS: Draft PR as I don't have Twistlock access at the moment to see if this actually fixes the CVEs. Have requested access to Twistlock!

[Draft] kafka-connect-bigquery CVEs: CCDB-4936, CCDB-4836 & CCDB-4835.

---

pom.xml

Bumping debezium version to resolve build errors

Merge Conflict Resolution from 1.1.x to 1.2.x

---

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryErrorResponses.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfigTest.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/write/row/BigQueryErrorResponsesTest.java

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 2.1.x to 2.2.x)

---

kcbq-api/pom.xml
kcbq-connector/pom.xml
pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 2.0.x to 2.1.x)

---

kcbq-api/pom.xml
kcbq-connector/pom.xml
pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 2.5.x to master)

---

kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryErrantRecordHandlerIT.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQuerySinkConnectorIT.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/UpsertDeleteBigQuerySinkConnectorWithSRIT.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/utils/SchemaRegistryTestUtils.java

Pint merge by jenkins is failing https://jenkins.confluent.io/job/tools-autotasks/job/tools-autotasks/job/apply-pint-merge/2177/console

Manual merge from 2.6.x to master

---

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/StorageWriteApiWriter.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryErrantRecordHandlerIT.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryStorageWriteApiSinkConnectorIT.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/GcpClientBuilderIT.java

Addresses CC-19648
Includes -
1. Integration test to verify basic flow with Json type
2. Integration test to verify basic flow with Avro SR based type
3. Integration test to verify Schema updates
4. Integration test to verify auto Table creation
5. Integration test to verify correct DLQ routing
6. Integration test to verify stream creation

Storage Write API Basic mode integration tests

---

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/storageApi/ApplicationStream.java

Storage Write API adds more logging 

---

Jenkinsfile

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 2.5.x to 2.6.x)

---

README.md
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQueryErrantRecordHandlerIT.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/BigQuerySinkConnectorIT.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/TimePartitioningIT.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/UpsertDeleteBigQuerySinkConnectorIT.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/integration/UpsertDeleteBigQuerySinkConnectorWithSRIT.java
pom.xml

JIRA - CC-22260
Backports following PRs to 2.5.x -
- https://github.com/confluentinc/kafka-connect-bigquery/pull/324
- https://github.com/confluentinc/kafka-connect-bigquery/pull/334
- https://github.com/confluentinc/kafka-connect-bigquery/pull/336
- https://github.com/confluentinc/kafka-connect-bigquery/pull/337

Backports required changes from 2.6.x to 2.5.x

---

.github/CODEOWNERS
.semaphore/project.yml
.semaphore/semaphore.yml
Jenkinsfile
pom.xml
service.yml
sonar-project.properties

[pint merge](https://jenkins.confluent.io/job/tools-autotasks/job/tools-autotasks/job/apply-pint-merge/build?delay=0sec) these changes after merging them.
1) Deletes the Jenkinsfile.
2) Adds the service-bot config (service.yml) and semaphore files generated by service-bot
[Read the background and motivation](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3033867557/CI+System+Migration+Jenkins-+Semaphore#Background-and-Motivation)  
Please merge this PR ASAP because we plan on shutting down Jenkins by the end of the year.

Migration: Jenkins -> Semaphore

---

.semaphore/semaphore.yml
service.yml

Adding changes as per Jenkins to Semaphore Migration one-pager. Since we have docs repo for this repo, adding the required changes. 
JIRA: CC-24775

Jenkins to semaphore migration

---

Jenkinsfile
pom.xml

Adds BigQuerySink connector to sonarQube
The coverage numbers have been taken for Jenkins test build numbers.

Add project to sonarQube

---

pom.xml

Fixes coverage number for tests 
JIRA: CC-23514

Fixes coverage numbers for tests

---

.semaphore/semaphore.yml

This PR increases the semaphore execution time limit to 2 hours.

Increase semaphore execution time

---

pom.xml

Update coverage numbers

---

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQueryHelper.java
kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/filter/GcpCredsFilter.java
kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/filter/GcpCredsFilterTest.java
kcbq-connector/src/test/resources/keyfile.json

Please refer to Jira ticket for details.

[CC-24136] Filter creds file to only required fields

---

kcbq-connector/pom.xml

https://confluentinc.atlassian.net/browse/CONMON-546
Removed vulnerable zookeeper dependency.

CONMON-546: Remove zookeeper dependency

---

kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/BigQuerySinkTask.java

Adds info log to track the working of the connector

Adds info log to track the working of the connector

---

pom.xml

Resolves merge conflicts encountered during pint merge

Merge conflict resolution from 1.6 to 2.0

---

pom.xml

merge conflicts resolution from 2.0.x o 2.1.x

merge conflicts resolution from 2.0.x o 2.1.x
